{% set name = "django-yugabytedb" %}
{% set version = "4.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-yugabytedb-{{ version }}.tar.gz
  sha256: a8dce19dc763afcd0725e49892017d44c26b58745bcc0da20c2a80a0810fdcba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=4.2

test:
  imports:
    - django_yugabytedb
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.yugabyte.com/
  summary: Django backend for YugabyteDB
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
